{
    "name": "Create Employees",
    "version": "14.0.1.0.0",
    "category": "Recruitment",
    "summary": "This module made for create new employees",
    "sequence": 1,
    "author": "Patel Akash",
    "website": "https://www.aktivesoftware.com/",
    "description": """""",
    "depends": ["hr_recruitment",],
    "data": [
        "security/ir.model.access.csv",
        "views/create_employees_views.xml",
        "views/hr_job_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
