{
    "name": "Create Employees",
    "version": "14.0.1.0.0",
    "category": "Recruitment",
    "summary": "This module made for create new employees",
    "sequence": 1,
    "author": "Patel Akash",
    "website": "https://www.aktivesoftware.com/",
    "description": """""",
    "depends": ["hr_recruitment","website"],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/create_employees_menu.xml",
        "data/employee_details_menu.xml",
        "views/assets.xml",
        "views/create_employees_views.xml",
        "views/hr_job_views.xml",
        "views/create_employees_template.xml",
        "views/employee_detail_template.xml",
        "views/portal_menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
