{
    "name": "Product Website",
    "version": "14.0.1.0.0",
    "category": "Website",
    "summary": "",
    "website": "https://www.aktivesoftware.com/",
    "description": "This is product website",
    "depends": ["website_sale"],
    "data": [
        "security/ir.model.access.csv",
        "data/product_website_data.xml",
        "views/assets.xml",
        "views/controllers_product_views.xml",
        "views/product_description_views.xml",
        "views/res_partner_views.xml",
        "views/contacts_list_views.xml",
        "views/contacts_form_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
